export enum ActivityCategory {
    FOOTPRINT = 'FOOTPRINT',
    STEPS = 'STEPS',
    WALKING_DISTANCE = 'WALKING_DISTANCE',
    CYCLING_DISTANCE = 'CYCLING_DISTANCE',
    PUBLIC_TRANSIT = 'PUBLIC_TRANSIT',
}
